### ISSUE TITLE
消息能够正常推送，但是日志有报错

### ISSUE THREAD

**Issue by koking0** [syrinka/nonebot-plugin-report#2]
![image](https://user-images.githubusercontent.com/45281765/192931938-639647c4-cf45-4f64-8706-cd2c629f25bb.png)

**Comment by syrinka** [comment]
这应该是 `nonebot-plugin-chatrecorder` 那边插件的问题

晚点我打个补丁吧

**Comment by syrinka** [comment]
请更新到 1.1.1，应该不会有问题了
