### ISSUE TITLE
有关于server酱

### ISSUE THREAD

**Issue by yhzcake** [syrinka/nonebot-plugin-report#8]
尝试将该插件用于使用server酱的webhook使用,但是接收不到信息,不知道有没有适配的打算

**Comment by syrinka** [comment]
适配什么？server酱是推送服务，这个插件也是推送服务，你是想将它们怎么一起用呢

**Comment by yhzcake** [comment]
server酱不是有个自定义webhook吗，但是我没搞懂他那个到底是怎么填的

**Comment by syrinka** [comment]
总之没有计划
